### ISSUE TITLE
Sin

### ISSUE THREAD

**Issue by Chanoski926** [Onewaysidewalks/col-reforger#1]
![Screenshot_Crusaders_2020-12-06-20-53-05-872](https://user-images.githubusercontent.com/75600173/101311296-f61cb300-3805-11eb-8df9-be2deedadf33.png)
![Screenshot_Crusaders_2020-12-06-20-52-58-218](https://user-images.githubusercontent.com/75600173/101311300-f74de000-3805-11eb-936d-572c96aede0a.png)
![Screenshot_Crusaders_2020-12-06-20-52-48-661](https://user-images.githubusercontent.com/75600173/101311302-f7e67680-3805-11eb-9fe2-d64e37a792f8.png)
![Screenshot_Crusaders_2020-12-06-20-52-40-601](https://user-images.githubusercontent.com/75600173/101311305-f87f0d00-3805-11eb-9785-4c51b9936349.png)
![Screenshot_Crusaders_2020-12-06-20-52-19-491](https://user-images.githubusercontent.com/75600173/101311306-f917a380-3805-11eb-9fdd-f49ce64f637d.png)
![Screenshot_Crusaders_2020-12-06-20-52-14-647](https://user-images.githubusercontent.com/75600173/101311308-f9b03a00-3805-11eb-9d72-1cc175841905.png)
![Screenshot_Crusaders_2020-12-06-20-52-06-643](https://user-images.githubusercontent.com/75600173/101311310-f9b03a00-3805-11eb-916f-c41c46ee4470.png)
![Screenshot_Crusaders_2020-12-06-20-52-00-456](https://user-images.githubusercontent.com/75600173/101311312-fae16700-3805-11eb-873c-fb07f0e60dc3.png)

**Comment by Onewaysidewalks** [comment]
thanks @Chanoski926 , would you be able to add screens when possible of the other possible skills? (looks like only flying blade and shadow blade so far). Id need a screenie of each skill on the right hand side (doesnt matter how much + or if double etc, just need a pic of each on the right). With it ill update the training/configuration accordingly

**Comment by Onewaysidewalks** [comment]
i took a stab at generating the necessary data for whats missing, let me know if you run into any issues

**Comment by Chanoski926** [comment]
It can't detect the reforge box. When I start the reforge.jar it would
click the outside of that reforge window
